/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./views/subPage/about.vue')['default']
    Alert: typeof import('./customUI/alert/alert.vue')['default']
    App: typeof import('./App.vue')['default']
    Aside: typeof import('./components/aside.vue')['default']
    Background: typeof import('./components/background.vue')['default']
    Card: typeof import('./components/card.vue')['default']
    CustomSelecter: typeof import('./customUI/selecter/selecter.vue')['default']
    Download: typeof import('./views/subPage/download.vue')['default']
    Feedback: typeof import('./views/subPage/feedback.vue')['default']
    Frame: typeof import('./views/frame.vue')['default']
    Launch: typeof import('./views/launch.vue')['default']
    Library: typeof import('./views/subPage/library.vue')['default']
    LoadingBox: typeof import('./customUI/loadingBox/loadingBox.vue')['default']
    Log: typeof import('./views/subPage/log.vue')['default']
    ManagerSettings: typeof import('./views/subPage/managerSettings.vue')['default']
    ModSettings: typeof import('./views/subPage/modSettings.vue')['default']
    More: typeof import('./views/more.vue')['default']
    Msgbox: typeof import('./customUI/msgbox/msgbox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selecter: typeof import('./customUI/selecter/selecter.vue')['default']
    SelectProfile: typeof import('./views/selectProfile.vue')['default']
    Settings: typeof import('./views/settings.vue')['default']
    Store: typeof import('./views/store.vue')['default']
  }
}
